# 넘파이(Numpy)
    - 파이썬을 활용한 데이터 분석에서 가장 기본이 되는 라이브러리
    - 넘파이로만으로도 많이 사용되지만, 판다스(pandas), 머신러닝 들 수많은 분야에서 기본적으로 사용되므로 파이썬 개발자의 필수 라이브러리이다.

[넘파이 공식 문서](https://numpy.org/)

### 1) 수학 수치연산(numerical python)
    - 합, 평균, 행렬연산 등이 가능하다
### 2) 기본 타입
    - ndarray (n-dimenstional array) 다차원 배열의 표현
### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다
    - 그 외 수 많은 모듈에서 numpy 함수명과 기능을 그대로 사용 가능하다

<img src="https://media.licdn.com/dms/image/v2/D4E22AQFKQ93ywmSGsg/feedshare-shrink_800/B4EZ.vxZJAHoAg-/0/1785360388974?e=2147483647&v=beta&t=qutjb0gyTs5FKZTWL_mxm1Xd_q22lPtZFuOiM5EAb5U" width="500"/>

In [2]:
import numpy as np

In [4]:
# arr1 = np.ndarray([1, 2, 3])
arr1 = np.array([1, 2, 3])

print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# 하나의 타입으로만 정의할 수 있다.
arr2 = np.array([      1, 2, 3])
arr2 = np.array([      1, 2, 3.0])

print(arr2)
print(arr2)

[1. 2. 3.]
[1. 2. 3.]


In [10]:
# 넘파이의 강제 승격, (이러한 경우에는 문자열로 들어가야 다 보여줄 수 있기 때문)
arr3 = np.array([1, 2, False, "홍길동", 12.5])

print(arr3)
print(type(arr3))

['1' '2' 'False' '홍길동' '12.5']
<class 'numpy.ndarray'>


In [11]:
arr3 = np.array([i + 1 for i in range(10)])

arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## ndarray의 인덱싱

In [15]:
print(arr3[1])
print(type(arr3[1]))
print(int(arr3[1]))

2
<class 'numpy.int32'>
2


## ndarray의 슬라이싱

In [24]:
print(arr3)
print(arr3[2:5])
print(arr3[::2])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]
[1 3 5 7 9]


### shape
    - numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서, 몇 개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
    - arr.shape의 결과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*렬을 곱하면 크기도 확인할 수 있다.

In [25]:
print(arr3.shape)

(10,)


In [27]:
arr4 = np.array([[2]])
arr4

array([[2]])

In [29]:
print(arr4.shape)

(1, 1)


In [31]:
#2차원 매트릭스
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5)
print(arr5.shape)

#2행3열(2차원)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [36]:
# 텐서
arr6 = np.array([[[1, 2, 3], [4, 5, 6]]])
print(arr6)
print(arr6.shape)

# 2행 3열 매트릭스가 1개(3차원)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [16]:
arr7 = np.array([
        [
            [10, 20, 30, 40],
            [50, 60, 70, 80],
            [90, 100, 110, 120],
        ],
        [
            [100, 200, 300, 400],
            [500, 600, 700, 800],
            [900, 1000, 1100, 1200],
        ],
    ])

print(arr7)
print(arr7.shape)

[[[  10   20   30   40]
  [  50   60   70   80]
  [  90  100  110  120]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]]
(2, 3, 4)


In [17]:
arr7.ndim #차원을 확인할 떄

3

In [41]:
#데이터의 개수
arr7.size

24

# np.arange()

In [4]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,5)

array([1, 2, 3, 4])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [3]:
# u: Unisigned(부호를 없애는 타입)
arr2 = np.arange(10, dtype=np.uint8)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

## 넘파이의 자료형
- int: 부호가 있는 정수(8, 16, 32, 64)
- uint: 부호가 없는 정수(8, 16, 32, 64)
- float: 실수(16, 32, 64, 128)
- complex: x복소수(64, 128, 256)
- bool: 불리언(8)
- string_: 문자열(8)
- object: 오브젝트(64)

# astype (타입)
- 기존의 배열을 복사하고 타입을 변경하고 싶을 때

In [10]:
arr2 = np.arange(10)

print(arr2.dtype)

int64


In [13]:
arr3 = arr2.astype(np.int8)
print(arr2.dtype)
print(arr3.dtype)
#데이터를 복사해서 타입변경?

int64
int8


## np.reshape()
- ndarray의 형태와 차원을 바꾸기 위해서 사용하는 메서드

In [19]:
arr3 = np.arange(12)

print(arr3.ndim)
print(arr3.shape)

1
(12,)


In [20]:
arr3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr3.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
arr3.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [24]:
arr3.reshape(2, 1, 2, 3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]]],


       [[[ 6,  7,  8],
         [ 9, 10, 11]]]])

In [25]:
arr3.reshape(1, 1, 4, 3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]]])

In [27]:
#reshape의 개수와, 데이터의 개수가 맞지않으면 오류
arr3.reshape(2, 2, 2, 2)

ValueError: cannot reshape array of size 12 into shape (2,2,2,2)

## np.ones(), np.zeros()
- ndarray의 초기값을 0또는 1로 설정하기 위한 메서드

In [29]:
arr5 = np.ones(8)
print(arr5)
print(type(arr5[0]))

[1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.float64'>


In [32]:
arr6 = np.zeros(64, dtype=np.int64)
print(arr6)
print(type(arr6[0]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
<class 'numpy.int64'>


In [36]:
arr6.reshape(16, 4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
arr6.reshape(4, 16)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
arr6.reshape(2, 2, 16)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

## np.random
- rand: 0 ~ 1 사이의 균일 분포
- randn: 정규분포
- randint: 균일분포 정규 난수
<img src="https://thebook.io/img/080263/218.jpg" />

In [39]:
np.random.randn(5)

array([-0.61034098,  1.11053262,  0.99508485,  0.95970806, -1.41431825])

In [132]:
np.random.randint(5)

2

In [133]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [140]:
np.random.randint(50,101)

65

In [157]:
# 로또번호 추첨
np.random.randint(1, 46, (2, 3))

# 와 나 진ㅉㅏ 하나도 모르겠네@@@@@@@@@@@@@@@@@@!!!!!!!!!!!!!!!!!!!

array([[25, 33, 17],
       [39,  2, 14]], dtype=int32)

## seed()
- 난수를 예측가능하도록 만들며, 실행할 때마다 동일한 난수를 발생시켜, 코드의 재현성, 특정 알고리즘의 결과를 재현하게 만든다.
    또한 해당 알고리즘의 결과의 오류를 추적하기 위해 사용한다.

In [169]:
np.random.seed(4885)
#추적하기 위한 값?
# “앞으로 랜덤 숫자를 뽑을 때 4885라는 시작점을 기준으로 뽑아라.”????

print(np.random.randint(10, size=(2, 5)))

[[9 1 0 3 4]
 [8 7 4 7 6]]


In [163]:
np.random.seed(4885)

# 0 ~ 1 까지의 균등분포
print(np.random.rand(10))

[0.21350835 0.56504926 0.7597468  0.05666448 0.6753598  0.36138766
 0.01299493 0.04721084 0.26603997 0.8042786 ]


## unique()
- ndarray의 중복값을 제거해주는 함수

In [164]:
np.unique([11, 11, 11, 11, 11, 14, 15])

array([11, 14, 15])

## shape 변경
ravel(), np.ravel()
- 다차원 배열을 1차원으로 변경하는 메서드

In [172]:
arr7 = np.arange(24).reshape(2, 3, 4)
arr7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [174]:
arr7.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [175]:
# C : row 방향
arr7.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [176]:
# F: column 방향 (acis(축): -1)
arr7.ravel(order='F')

array([ 0, 12,  4, 16,  8, 20,  1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10,
       22,  3, 15,  7, 19, 11, 23])

## np.flatten()
- copy를 생성하고 원본 배열을 변경하지 않는 복사본을 반환한다.

In [179]:
arr7 = np.arange(24).reshape(2, 12)
print(arr7)
print(arr7.flatten())

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [180]:
arr7 = np.arange(24).reshape(2, 3, 4)
print(arr7)
print(arr7.flatten())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [185]:
arr8 = np.arange(120).reshape(2, -1, 12)
# -1을 넣어주면 차원을 유추해서 뽑아냄

In [184]:
arr8

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

## 차원 확장
- np.expand_dims()
- axis로 지정된 축을 확장시키는 메서드

In [189]:
arr8 = np.arange(10)

print(arr8.shape)

(10,)


In [191]:
arr9 = np.expand_dims(arr8, axis=0)

print(arr9.shape)

(1, 10)


In [196]:
arr9 = np.expand_dims(arr8, axis=1)
print(arr9)
print(arr9.shape)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


## 차원축소
- squeeze(), np.squeeze()

In [195]:
print(arr9)
print(arr9.squeeze())

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]


## 전치 행렬(transpose) T

In [198]:
# 2, 3 -> 3, 2
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [199]:
np.transpose(arr1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [203]:
arr2 = np.arange(12).reshape(2, 6)

In [204]:
arr2.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [205]:
print(arr2.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## array간의 연산

In [207]:
# 리스트간의 연산
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [211]:
# array + scalar 는 연산이 됨
# 2차원 + 0차원 > 큰 차원으로 계산이 된거임
arr1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [209]:
# 2차원 + 1차원
arr1 + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [210]:
# 2차원 + 2차원
arr1 + [[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [213]:
# 2차원 + 3차원 => 3차원으로 계산. 차원이 늘어남 >>브로드캐스팅
arr1 + [[[10]]]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

## 브로드캐스팅
- 다른 크기의 배열들 간에도 자동으로 연산해주는 Numpy의 강력한 기능

## 브로드캐스팅의 특징
    - 기본적으로는 shape와 같은 두 ndarray에 대한 연산은 각 원소별로 진행한다
    - 다른 shape를 갖는 array 간의 연산의 경우 브로드 캐스팅(shape를 맞춤) 후 진행한다

<img width=500 src='https://www.astroml.org/_images/fig_broadcast_visual_1.png' />

In [221]:
arr1 = np.arange(12).reshape(4, 3)
arr1

print(arr1)
print(arr1.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [222]:
arr2 = np.arange(3)
arr2

print(arr2)
print(arr2.shape)

[0 1 2]
(3,)


In [223]:
print(arr1 + arr2)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


## 브로드 캐스팅의 규칙
1. 뒷 차원부터 비교한다.
2. shape가 같아야 한다.
3. 차원 중 값이 1이 존재해야 한다.

[브로드캐스팅 공식문서](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [225]:
"""
    차원에 1이 존재하는 경우 확장이 가능하다.
    6 x 1 x 5
        7 x 3

    6 x 7 x 5
"""

None

In [226]:
arr1 = np.arange(100, 104)
print(arr1)

[100 101 102 103]


In [227]:
# (4, 3)
arr2 = np.arange(12).reshape(4, 3)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [234]:
# 불가능함!
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

# 이유:
<img src="https://numpy.org/doc/stable/_images/broadcasting_3.png" />

In [239]:
# (2, 3), (3, 2)
arr3 = np.arange(6).reshape(2, 3)

arr4 = np.arange(100, 106).reshape(3, 2)

print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[100 101]
 [102 103]
 [104 105]]


In [242]:
arr3.T + arr4

array([[100, 104],
       [103, 107],
       [106, 110]])

## 차원축(axis)
- 1차원 array라면 각 차원에 대한 axis 값은 0
- 2차원 array라면 각 차원에 대한 axis 값은 0, 1
- 3차원 array라면 각 차원에 대한 axis 값은 0, 1, 2

In [244]:
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [246]:
np.sum(arr1, axis = 0)

np.int64(105)

In [248]:
arr1 = np.arange(15).reshape(3, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [249]:
np.sum(arr1, axis=0)

array([15, 18, 21, 24, 27])

In [251]:
np.sum(arr1, axis=1)

array([10, 35, 60])

In [254]:
arr2 = np.arange(24).reshape(2, 3, 4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [260]:
np.sum(arr2, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [257]:
np.sum(arr2, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [258]:
np.sum(arr2, axis=-1)

array([[ 6, 22, 38],
       [54, 70, 86]])

## 중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
## argmax()
- 최대값의 인덱스

In [263]:
arr3 = np.arange(5,10)
print(arr3)
print(arr3[arr3.argmax()])

[5 6 7 8 9]
9


In [269]:
np.random.seed(918)

arr4 = np.random.randint(10, size = (1, 6)).flatten()

print(arr4.argmax()) # 가장 큰 값의 인덱스
print(arr4.argmin()) # 가장 큰 값의 인덱스
print(arr4.max()) # 가장 큰 값
print(arr4.min()) # 가장 값은 값4

print(np.argmax(arr4))

0
4
9
2
0


In [295]:
arr5 = np.random.randint(10, size=(3, 6))
arr5

array([[7, 8, 0, 2, 4, 4],
       [7, 4, 2, 2, 6, 1],
       [9, 5, 8, 5, 5, 9]], dtype=int32)

In [296]:
print(arr5.argmax(axis=0))

[2 0 2 2 1 2]


In [302]:
print(arr5.argmax(axis=1))

[1 0 0]


In [303]:
print(arr5.max(axis=0))

[9 8 8 5 6 9]


In [305]:
print(arr5.min(axis=0))

[7 4 0 2 4 1]


## boolean selection, boolean indexing
- array 인덱싱 시, bool 타입의 조건에 맞는 list를 전달하여 조건식을 만족하는 True의 결과물만 필터링한다.

In [306]:
arr4 = np.random.randint(1, 100, size=20)
print(arr4)

[32  9 15 29 59 49 87 71 32 12 75 18 33 66 49 37 89 34 70 15]


In [307]:
arr4 * 5

array([160,  45,  75, 145, 295, 245, 435, 355, 160,  60, 375,  90, 165,
       330, 245, 185, 445, 170, 350,  75], dtype=int32)

In [309]:
even_mask = arr4 % 2 == 0
arr4[even_mask]

array([32, 32, 12, 18, 66, 34, 70], dtype=int32)

## 다중 조건식
- &: and 조건식
- |: or 조건식

In [3]:
# 홀수이면서 50보다 작은 값
# and:
np.random.seed(2026)
arr5 = np.random.randint(100, size=15)
arr5

array([75, 68, 68,  6, 84, 70, 21, 11, 22, 85, 41, 58, 37, 20, 18],
      dtype=int32)

In [8]:
is_bound = (arr5 % 2 == 1) & (arr5 < 50)
arr5[is_bound]

array([21, 11, 41, 37], dtype=int32)

In [9]:
arr5[is_bound].astype(str)

array(['21', '11', '41', '37'], dtype='<U11')