# 판다스(Pandas)
   - 데이터 분석 라이브러리
   - 행(row), 열(column) 형태의 정형 데이터 객체를 다룬다.
   
## 2차원 데이터
   - 엑셀의 시트, RDB의 테이블과 같은 형태이다.
   - 대표적인 객체 DataFrame, Series
   
## Series
   - Pandas의 기본 객체 중 하나로, numpy의 ndarray를 기반으로 인덱싱 기능이 추가된
   1차원 배열을 나타낸다. (index x value의 형태)
   - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성한다
   - index를 지정할 경우 명시적으로 지정된 index를 사용한다.
   - 같은 타입의 0개 이상의 데이터를 가질 수 있다

[판다스 공식문서](https://pandas.pydata.org/)

In [2]:
import numpy as np
import pandas as pd

In [5]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [8]:
# 메서드가 아님 !! 초기값넣을수잇긔
pd.Series(arr1)

0    1
1    2
2    3
dtype: int64

In [11]:
s1 = pd.Series(arr1, index=['a', 'b', 'c'])

s1

a    1
b    2
c    3
dtype: int64

In [13]:
print(s1['a'])

1


In [16]:
s2 = pd.Series([(i + 1) * 10 for i in range(5)])
s2

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [18]:
s2[0]

np.int64(10)

## 중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
## 주요필드
- valuse: pd의 해당값들을 반환하는 필드
- index: pd의 index를 반환하는 필드
- dtype: 현재 pd의 타입을 반환하는 필드

In [19]:
s2.values

array([10, 20, 30, 40, 50])

In [20]:
s2.index

RangeIndex(start=0, stop=5, step=1)

In [21]:
s2.dtype

dtype('int64')

In [23]:
names = ["홍길동", "장보고", "이순신"]
scores = [70, 80, 65]

#값을 명시해서 넣는 것을 권장한다
pd.Series(data=scores, index=names)

홍길동    70
장보고    80
이순신    65
dtype: int64

In [32]:
incomes = {
    "한혜진": 1500000,
    "이상아": 50000,
    "오승현": 500000,
    "이예나": 1000000,
    "김진휘": 57000000,
    "한보리": 77000000,
    "한우물": -10000
}

print(incomes.keys())
print(incomes.values())


# 굳이 키랑 벨류 자리에 따로 빼서 넣을 필요없이 시리즈로 한번에 만들기 가능!
pd.Series(incomes)

dict_keys(['한혜진', '이상아', '오승현', '이예나', '김진휘', '한보리', '한우물'])
dict_values([1500000, 50000, 500000, 1000000, 57000000, 77000000, -10000])


한혜진     1500000
이상아       50000
오승현      500000
이예나     1000000
김진휘    57000000
한보리    77000000
한우물      -10000
dtype: int64

In [34]:
s3 = pd.Series(incomes)

print(s3)

한혜진     1500000
이상아       50000
오승현      500000
이예나     1000000
김진휘    57000000
한보리    77000000
한우물      -10000
dtype: int64


In [36]:
s3["오승현":"한보리"]

오승현      500000
이예나     1000000
김진휘    57000000
한보리    77000000
dtype: int64

In [59]:
incomes = {
    "한혜진": 1500000,
    "이상아": 50000,
    "오승현": 500000,
    "이예나": 1000000,
    "김진휘": 57000000,
    "채진성": 500000,
    "한우물": -10000
}

print(incomes.keys())
print(incomes.values())

dict_keys(['한혜진', '이상아', '오승현', '이예나', '김진휘', '채진성', '한우물'])
dict_values([1500000, 50000, 500000, 1000000, 57000000, 500000, -10000])


In [60]:
# 한혜진의 수익을 -50000으로 변경

s3["한혜진"] = -50000

print(s3)

한혜진      -50000
이상아       50000
오승현      500000
이예나     1000000
김진휘    57000000
한보리    77000000
한우물      -10000
dtype: int64


In [56]:
s3["이예나"]
print(type(s3["이예나"]))

s3[["이예나"]]
print(type(s3[["이예나"]]))

<class 'numpy.int64'>
<class 'pandas.Series'>


In [73]:
s4 = s3[["이상아","한보리"]] 
# view만 제공
s3[["이상아","한보리"]] = 10, 10

In [64]:
s3

한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
한보리          10
한우물      -10000
dtype: int64

In [75]:
s4['이상아'] = 100

s4

이상아    100
한보리     10
dtype: int64

In [77]:
s4 = s3.copy()

s4

한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
한보리          10
한우물      -10000
dtype: int64

In [80]:
s3.name = "수익"
s3.index.name = "이름"
s3

이름
한혜진      -50000
이상아          10
오승현      500000
이예나     1000000
김진휘    57000000
한보리          10
한우물      -10000
Name: 수익, dtype: int64

## Series 함수
    - ndim : 차원 반환
    - len : 데이터 길이
    - size : 개수 반환
    - shape : 튜플의 형태로 shape반환
    - unique : 유일한 값만 udarray로 반환
    - count : NaN을 제외한 개수를 반환
    - mean : NaN를 제외한 평균
    - value_counts : NaN를 제외하고 각 값들의 빈도를 반환
## NaN(Not a Number)
- 숫자형 데이터가 들어와야 하는데 숫자형 데이터가 아닌 다른 값이 들어왔을 때 나타나는 값
- ex) DBMS -> null, JS -> undefuned, python -> None

In [81]:
s1 = pd.Series([10, 2, 3, 3, np.nan, 2, 3, 5, 7, 8, np.nan, np.nan])

s1

0     10.0
1      2.0
2      3.0
3      3.0
4      NaN
5      2.0
6      3.0
7      5.0
8      7.0
9      8.0
10     NaN
11     NaN
dtype: float64

In [82]:
s1.size

12

In [83]:
s1.shape

(12,)

In [84]:
s1.unique()

array([10.,  2.,  3., nan,  5.,  7.,  8.])

In [87]:
# NaN 데이터가 있다!
print(s1.count())
print(len(s1))

9
12


In [88]:
s1.value_counts()

3.0     3
2.0     2
10.0    1
5.0     1
7.0     1
8.0     1
Name: count, dtype: int64

In [91]:
# head의 디폴트는 5
s1.head()
s1.head(3)

0    10.0
1     2.0
2     3.0
dtype: float64

In [95]:
# 이것도 디폴트는 5 (뒤에서부터 가져오기)
s1.tail()
s1.tail(1)

11   NaN
dtype: float64

## 시리즈(Series)의 연산
- 시리즈는 시리즈끼리 연산이 가능하다. 단, index를 기준으로 연산된다.
- 이 특징은 DataFrame에서도 동일하게 적용된다.

In [97]:
products = {
    "난리부르스 치킨": 30000,
    "요아정 벌집 요거트": 50000,
    "그릭 요거트": 13000,
    "커피": 6000,
    "떡볶이": 20000,
    "예나가 만든 샌드위치": 50000
}

s2 = pd.Series(products)
s2

난리부르스 치킨       30000
요아정 벌집 요거트     50000
그릭 요거트         13000
커피              6000
떡볶이            20000
예나가 만든 샌드위치    50000
dtype: int64

In [102]:
products2 = {
    "난리부르스 치킨": 30000,
    "요아정 벌집 요거트": 50000,
    "국밥": 13000,
    "라면": 6000,
    "두쫀쿠": 10000,
    "피자": 30000
}

s3 = pd.Series(products2)
s3

난리부르스 치킨      30000
요아정 벌집 요거트    50000
국밥            13000
라면             6000
두쫀쿠           10000
피자            30000
dtype: int64

In [101]:
s2 + s3

국밥                  NaN
그릭 요거트              NaN
난리부르스 치킨        60000.0
두쫀쿠                 NaN
떡볶이                 NaN
라면                  NaN
예나가 만든 샌드위치         NaN
요아정 벌집 요거트     100000.0
커피                  NaN
피자                  NaN
dtype: float64

In [104]:
s2 * 1.2

난리부르스 치킨       36000.0
요아정 벌집 요거트     60000.0
그릭 요거트         15600.0
커피              7200.0
떡볶이            24000.0
예나가 만든 샌드위치    60000.0
dtype: float64

In [110]:
# 가격이 3만원을 넘는 괘씸한 음식을 골라내기
price_mask = s2 > 30000
s2[price_mask]

요아정 벌집 요거트     50000
예나가 만든 샌드위치    50000
dtype: int64

In [132]:
hobbies = {
    "승현": "칵테일방, 찜질방, 노래방",
    "예나": "요리, 노래방, 영화",
    "진성": "호프, 노래방, 호프집",
    "가나디": "그릭요거트, 그림그리기, 영화",
    "지혁": "음주, 흡연, 도박",
    "시우": "볼링, 클라이밍, 보석십자수"
}

s4 = pd.Series(hobbies)
s4

승현       칵테일방, 찜질방, 노래방
예나          요리, 노래방, 영화
진성         호프, 노래방, 호프집
가나디    그릭요거트, 그림그리기, 영화
지혁           음주, 흡연, 도박
시우      볼링, 클라이밍, 보석십자수
dtype: str

In [170]:
# 악의 축 mask로 제거하기
# s4.str.contains("호프|도박|흡연")


#각 행을 접근해서 글자들이 포함되어 있으면 True,아니면 False
hobbie_mask = s4.str.contains("호프|도박|흡연")
s5 = s4[-hobbie_mask]

In [168]:
evil_list = ["호프","도박","흡연"]
# @@@@@@@@@@@@@@@@@@@ 이중 반복문 컴프리헨션??????????????????????@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
evil_mask = [sum(evil in hobby for evil in evil_list) == 0 for hobby in s4]

evil_member = s4[evil_mask]
print(evil_member)

승현       칵테일방, 찜질방, 노래방
예나          요리, 노래방, 영화
가나디    그릭요거트, 그림그리기, 영화
시우      볼링, 클라이밍, 보석십자수
dtype: str


In [169]:
for hobby in s4:
    for evil in evil_list:
        print(evil in hobby)
    print()

False
False
False

False
False
False

True
False
False

False
False
False

False
True
True

False
False
False



## Series 값 삭제: drop()
- 해당 컬럼을 삭제하고, 복제본을 반환한다.

In [179]:
s3 = pd.Series(data=np.arange(100, 105), index=['a', 'b', 'c', 'd', 'e'])
s3

a    100
b    101
c    102
d    103
e    104
dtype: int64

In [180]:
s3.drop('a', inplace=True)
s3
#원본을 건드림

b    101
c    102
d    103
e    104
dtype: int64

In [181]:
s3.drop(['b','c'])

d    103
e    104
dtype: int64

## .groupby()

In [187]:
salary_list = [
    "지혁", "희수", "승현", "우영", "희수", "시우", "슬기", "상아", "상아", "희수", "우영", "진휘", 
    "지혁", "준승", "예나", "진휘", "지호", "지혁", "희수", "승현", "시우", "준승", "우영", "예나"
]

salary_income = [
    200, 300, 400, 400, 350, 500, 300, 600, 600, 500, 600, 800,
    300, 300, 500, 500, 300, 400, 300, 800, 300, 200, 700, 500,
]

In [188]:
s1 = pd.Series(data=salary_income, index=salary_list)
s1

지혁    200
희수    300
승현    400
우영    400
희수    350
시우    500
슬기    300
상아    600
상아    600
희수    500
우영    600
진휘    800
지혁    300
준승    300
예나    500
진휘    500
지호    300
지혁    400
희수    300
승현    800
시우    300
준승    200
우영    700
예나    500
dtype: int64

In [191]:
# .count(): 개수
s1.groupby(s1.index).count()

상아    2
슬기    1
승현    2
시우    2
예나    2
우영    3
준승    2
지혁    3
지호    1
진휘    2
희수    4
dtype: int64

In [192]:
s1.groupby(s1.index).sum()

상아    1200
슬기     300
승현    1200
시우     800
예나    1000
우영    1700
준승     500
지혁     900
지호     300
진휘    1300
희수    1450
dtype: int64

In [195]:
# mean: 평균
s1.groupby(s1.index).mean()

상아    600.000000
슬기    300.000000
승현    600.000000
시우    400.000000
예나    500.000000
우영    566.666667
준승    250.000000
지혁    300.000000
지호    300.000000
진휘    650.000000
희수    362.500000
dtype: float64

In [196]:
s1.groupby(s1 > 300).count()

False     9
True     15
dtype: int64

In [197]:
s1.groupby(s1 > 300).mean()

False    277.777778
True     543.333333
dtype: float64

In [202]:
# 600만원 이상 받은 사용자의 수
s1.groupby(s1 >= 600).count()

False    18
True      6
dtype: int64

In [203]:
# apply: 형태를 바꾸는거
s1.groupby(s1 >= 600).apply(list)

False    [200, 300, 400, 400, 350, 500, 300, 500, 300, ...
True                        [600, 600, 600, 800, 800, 700]
dtype: object

In [204]:
s1.groupby(s1 >= 600).apply(lambda x: list((x.index)))


False    [지혁, 희수, 승현, 우영, 희수, 시우, 슬기, 희수, 지혁, 준승, 예나, 진...
True                              [상아, 상아, 우영, 진휘, 승현, 우영]
dtype: object

In [207]:
s1.groupby(s1 >= 600).apply(lambda x: list(zip(x.index, x)))


False    [(지혁, 200), (희수, 300), (승현, 400), (우영, 400), (...
True     [(상아, 600), (상아, 600), (우영, 600), (진휘, 800), (...
dtype: object

In [209]:
# 메서드 이름에 to로 시작하는 애들은 형변환임, is 로 시작하는애들은 bool 타임 get은 getter 값을 가져오느ㄴ거 set은 setter값변환

s1.to_dict()
s1.to_list()

[200,
 300,
 400,
 400,
 350,
 500,
 300,
 600,
 600,
 500,
 600,
 800,
 300,
 300,
 500,
 500,
 300,
 400,
 300,
 800,
 300,
 200,
 700,
 500]